services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - plataforma-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  discovery-server:
    container_name: discovery-server
    build:
      context: .
      dockerfile: ./infra/discovery-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - plataforma-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: on-failure

  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: ./infra/config-server/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - plataforma-network
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: on-failure

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./core/gateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - plataforma-network
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    restart: on-failure

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./core/auth-service/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - plataforma-network
    depends_on:
      mongodb:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/plataforma_auth_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    restart: on-failure

  tenantservice:
    container_name: tenantservice
    build:
      context: .
      dockerfile: ./core/tenant-service/Dockerfile
    networks:
      - plataforma-network
    depends_on:
      mongodb:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/plataforma_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    restart: on-failure

volumes:
  mongo-data:

networks:
  plataforma-network:
    driver: bridge
