spring:
  application:
    # Nome do servi\u00E7o para o Config Server e Eureka
    name: gateway
  config:
    # Busca a configura\u00E7\u00E3o no Config Server (conex\u00E3o obrigat\u00F3ria)
    import: "configserver:"
  cloud:
    config:
      # Usa o Discovery (Eureka) para encontrar o Config Server
      discovery:
        enabled: true
        service-id: config-server
      # For\u00E7a o servi\u00E7o a esperar pelo Config Server
      fail-fast: true
      retry:
        max-attempts: 30
        initial-interval: 2000

# Endere\u00E7o do Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/