spring:
  application:
    name: tenant-service
  config:
    # Conexão com o Config Server agora é OBRIGATÓRIA
    import: "configserver:"
    # E com o fail-fast, ele será forçado a usar as retentativas
    fail-fast: true
    retry:
      max-attempts: 30
      initial-interval: 2000
      max-interval: 5000
      multiplier: 1.3
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true # Garante que o IP do contêiner seja registrado no Eureka
